# Generated by Django 3.2.7 on 2021-09-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateField(auto_now_add=True)),
                ('image_raw', models.ImageField(upload_to='static/image_raw')),
                ('image_converted', models.ImageField(upload_to='static/image_converted')),
            ],
        ),
    ]
