# Generated by Django 3.2.7 on 2021-09-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_convert', '0002_auto_20210930_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_converted',
            field=models.ImageField(upload_to='image_converted'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_raw',
            field=models.ImageField(upload_to='image_raw'),
        ),
    ]
